config/routes.rb
Rails.application.routes.draw do
  devise_for :admins

  authenticated :admin do
    resources :hogar_proyects
    resources :industrial_proyects
    resources :contacts
  end


  resources :contacts,  only: [:create]
  resources :hogar_proyects, only: [:index, :show]
  resources :hadjuntos, only: [:create, :destroy, :new]
  resources :industrial_proyects, only: [:index, :show]
  resources :iadjuntos, only: [:create, :destroy, :new]
  

  root 'home#index'

  get 'industria/index'

  get 'hogar/index'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/industrial_proyect.rb
class IndustrialProyect < ApplicationRecord
  has_many :iadjuntos
end

app/controllers/industrial_proyects_controller.rb
class IndustrialProyectsController < ApplicationController
  before_action :set_industrial_proyect, only: [:show, :edit, :update, :destroy]

  # GET /industrial_proyects
  # GET /industrial_proyects.json
  def index
    @industrial_proyects = IndustrialProyect.all
  end

  # GET /industrial_proyects/1
  # GET /industrial_proyects/1.json
  def show
    @iadjunto = Iadjunto.new
  end

  # GET /industrial_proyects/new
  def new
    @industrial_proyect = IndustrialProyect.new
  end

  # GET /industrial_proyects/1/edit
  def edit
  end

  # POST /industrial_proyects
  # POST /industrial_proyects.json
  def create
    @industrial_proyect = IndustrialProyect.new(industrial_proyect_params)

    respond_to do |format|
      if @industrial_proyect.save
        format.html { redirect_to @industrial_proyect, notice: 'Industrial proyect was successfully created.' }
        format.json { render :show, status: :created, location: @industrial_proyect }
      else
        format.html { render :new }
        format.json { render json: @industrial_proyect.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /industrial_proyects/1
  # PATCH/PUT /industrial_proyects/1.json
  def update
    respond_to do |format|
      if @industrial_proyect.update(industrial_proyect_params)
        format.html { redirect_to @industrial_proyect, notice: 'Industrial proyect was successfully updated.' }
        format.json { render :show, status: :ok, location: @industrial_proyect }
      else
        format.html { render :edit }
        format.json { render json: @industrial_proyect.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /industrial_proyects/1
  # DELETE /industrial_proyects/1.json
  def destroy
    @industrial_proyect.destroy
    respond_to do |format|
      format.html { redirect_to industrial_proyects_url, notice: 'Industrial proyect was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_industrial_proyect
      @industrial_proyect = IndustrialProyect.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def industrial_proyect_params
      params.require(:industrial_proyect).permit(:name, :description, :large_description)
    end
end

app/helpers/industrial_proyects_helper.rb
module IndustrialProyectsHelper
end

app/views/industrial_proyects/_form.html.erb
<%= form_for(industrial_proyect) do |f| %>
  <% if industrial_proyect.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(industrial_proyect.errors.count, "error") %> prohibited this industrial_proyect from being saved:</h2>

      <ul>
      <% industrial_proyect.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :large_description %>
    <%= f.text_area :large_description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/industrial_proyects/edit.html.erb
<h1>Editing Industrial Proyect</h1>

<%= render 'form', industrial_proyect: @industrial_proyect %>

<%= link_to 'Show', @industrial_proyect %> |
<%= link_to 'Back', industrial_proyects_path %>

app/views/industrial_proyects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Industrial Proyects</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Large description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @industrial_proyects.each do |industrial_proyect| %>
      <tr>
        <td><%= industrial_proyect.name %></td>
        <td><%= industrial_proyect.description %></td>
        <td><%= industrial_proyect.large_description %></td>
        <td><%= link_to 'Show', industrial_proyect %></td>
        <td><%= link_to 'Edit', edit_industrial_proyect_path(industrial_proyect) %></td>
        <td><%= link_to 'Destroy', industrial_proyect, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if admin_signed_in? %>
  <%= link_to 'New Industrial Proyect', new_industrial_proyect_path %>
<% end %>

app/views/industrial_proyects/new.html.erb
<h1>New Industrial Proyect</h1>

<%= render 'form', industrial_proyect: @industrial_proyect %>

<%= link_to 'Back', industrial_proyects_path %>

app/views/industrial_proyects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @industrial_proyect.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @industrial_proyect.description %>
</p>

<p>
  <strong>Large description:</strong>
  <%= @industrial_proyect.large_description %>
</p>

<% if admin_signed_in? %>
  <%= render 'iadjuntos/form', industrial_proyect_id: @industrial_proyect.id %>
<% end %>
<ul>
  <% @industrial_proyect.iadjuntos.each do |li| %>
    <li>
      <p>
        <%= image_tag (li.imagen.url) %>
          <span><%=  link_to "x", li, method: :delete %></span>
        </p>
    </li>
  <% end %>
</ul>

<%= link_to 'Edit', edit_industrial_proyect_path(@industrial_proyect) %> |
<%= link_to 'Back', industrial_proyects_path %>