config/routes.rb
Rails.application.routes.draw do
  devise_for :admins

  authenticated :admin do
    resources :hogar_proyects
    resources :industrial_proyects
    resources :contacts
  end


  resources :contacts,  only: [:create]
  resources :hogar_proyects, only: [:index, :show]
  resources :hadjuntos, only: [:create, :destroy, :new]
  resources :industrial_proyects, only: [:index, :show]
  resources :iadjuntos, only: [:create, :destroy, :new]
  

  root 'home#index'

  get 'industria/index'

  get 'hogar/index'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates_presence_of :name, length: {minimum:5}, message: "Tu nombre es requerido para el contacto"
  validates_presence_of :email, length: {minimum:5}, message: "Tu correo es requerido para el contacto"
  validates_presence_of :body, message: "Necesitamos que nos comentes que necesitas"
end

app/models/hadjunto.rb
class Hadjunto < ApplicationRecord
  belongs_to :hogar_proyect

  has_attached_file :imagen, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :imagen, content_type: /\Aimage\/.*\z/
end

app/models/hogar_proyect.rb
class HogarProyect < ApplicationRecord
  has_many :hadjuntos
end

app/models/iadjunto.rb
class Iadjunto < ApplicationRecord
  belongs_to :industrial_proyect

  has_attached_file :imagen, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :imagen, content_type: /\Aimage\/.*\z/
end

app/models/industrial_proyect.rb
class IndustrialProyect < ApplicationRecord
  has_many :iadjuntos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  # def new
  #   @contact = Contact.new
  # end
  #
  # # GET /contacts/1/edit
  # def edit
  # end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:name, :email, :body)
    end
end

app/controllers/hadjuntos_controller.rb
class HadjuntosController < ApplicationController
  before_action :set_hadjunto, only: [:destroy]
  before_action :set_hogar_proyect, only: [:destroy]
  before_action :authenticate_hogar_proyect!

  def new
  end

  def create
    @hadjunto = Hadjunto.new(hadjunto_params)
    if @hadjunto.save
      redirect_to @hadjunto.hogar_proyect, notice: "Se guardo en la lista"
    else
      redirect_to @hogar_proyect, notice: "No se subio nada"
    end
  end

  def destroy
    @hadjunto.destroy
    redirect_to @hogar_proyect
  end

  private
    def authenticate_hogar_proyect!
      if params.has_key? :hadjunto
        @hogar_proyect = HogarProyect.find(params[:hadjunto][:hogar_proyect_id])
      end
      if @hogar_proyect.nil?
        redirect_to root_path, notice: "no puedes editar un hogar_proyecto ageno"
        return
      end
    end
    def hadjunto_params
      params.require(:hadjunto).permit(:hogar_proyect_id, :imagen)
    end
    def set_hadjunto
      @hadjunto = Hadjunto.find(params[:id])
    end
    def set_hogar_proyect
      @hogar_proyect = @hadjunto.hogar_proyect
    end
end

app/controllers/hogar_controller.rb
class HogarController < ApplicationController
  def index
    @contact = Contact.new
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @contact = Contact.new
  end
end

app/controllers/iadjuntos_controller.rb
class IadjuntosController < ApplicationController
  before_action :set_iadjunto, only: [:destroy]
  before_action :set_industrial_proyect, only: [:destroy]
  before_action :authenticate_industrial_proyect!

  def new
  end

  def create
    @iadjunto = Iadjunto.new(iadjunto_params)
    if @iadjunto.save
      redirect_to @iadjunto.industrial_proyect, notice: "Se guardo en la lista"
    else
      redirect_to @industrial_proyect, notice: "No se subio nada"
    end
  end

  def destroy
    @iadjunto.destroy
    redirect_to @industrial_proyect
  end

  private
    def authenticate_industrial_proyect!
      if params.has_key? :iadjunto
        @industrial_proyect = IndustrialProyect.find(params[:iadjunto][:industrial_proyect_id])
      end
      if @industrial_proyect.nil?
        redirect_to root_path, notice: "no puedes editar un industrial_proyecto ageno"
        return
      end
    end
    def iadjunto_params
      params.require(:iadjunto).permit(:industrial_proyect_id, :imagen)
    end
    def set_iadjunto
      @iadjunto = Hadjunto.find(params[:id])
    end
    def set_industrial_proyect
      @industrial_proyect = @iadjunto.industrial_proyect
    end
end

app/controllers/industria_controller.rb
class IndustriaController < ApplicationController
  def index
    @contact = Contact.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/hadjuntos_helper.rb
module HadjuntosHelper
end

app/helpers/hogar_helper.rb
module HogarHelper
end

app/helpers/hogar_proyects_helper.rb
module HogarProyectsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/iadjuntos_helper.rb
module IadjuntosHelper
end

app/helpers/industria_helper.rb
module IndustriaHelper
end

app/helpers/industrial_proyects_helper.rb
module IndustrialProyectsHelper
end

app/views/contacts/_form.html.erb
<%= form_for(@contact, remote: true, validate: true, html: {id: "contacto", class: "contacto"}) do |f| %>
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% @contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control", placeholder: "Nombre" %>
  </div>

  <div class="form-group">
    <%= f.label :email %>
    <%= f.email_field :email, class: "form-control", placeholder: "Correo" %>
  </div>

  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, class: "form-control", placeholder: "¿En que te podemos ayudar?" %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Contacts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.name %></td>
        <td><%= contact.email %></td>
        <td><%= contact.body %></td>
        <td><%= link_to 'Show', contact %></td>
        <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
        <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact', new_contact_path %>

app/views/contacts/new.html.erb
<h1>New Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Back', contacts_path %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @contact.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @contact.email %>
</p>

<p>
  <strong>Body:</strong>
  <%= @contact.body %>
</p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>

app/views/hadjuntos/_form.html.erb
<%= form_for (@hadjunto) do |f| %>
  <% if @hadjunto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @hadjunto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :hogar_proyect_id, value: hogar_proyect_id %>

  <div class="field">
    <%= f.label :list %><br>
    <%= f.file_field :imagen %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/hadjuntos/create.html.erb
<h1>Hadjuntos#create</h1>
<p>Find me in app/views/hadjuntos/create.html.erb</p>

app/views/hadjuntos/destroy.html.erb
<h1>Hadjuntos#destroy</h1>
<p>Find me in app/views/hadjuntos/destroy.html.erb</p>

app/views/hadjuntos/new.html.erb
<h1>Hadjuntos#new</h1>
<p>Find me in app/views/hadjuntos/new.html.erb</p>

app/views/iadjuntos/_form.html.erb
<%= form_for (@iadjunto) do |f| %>
  <% if @iadjunto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @iadjunto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :industrial_proyect_id, value: industrial_proyect_id %>

  <div class="field">
    <%= f.label :list %><br>
    <%= f.file_field :imagen %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/iadjuntos/create.html.erb
<h1>Iadjuntos#create</h1>
<p>Find me in app/views/iadjuntos/create.html.erb</p>

app/views/iadjuntos/destroy.html.erb
<h1>Iadjuntos#destroy</h1>
<p>Find me in app/views/iadjuntos/destroy.html.erb</p>

app/views/iadjuntos/new.html.erb
<h1>Iadjuntos#new</h1>
<p>Find me in app/views/iadjuntos/new.html.erb</p>