config/routes.rb
Rails.application.routes.draw do
  devise_for :admins

  authenticated :admin do
    resources :hogar_proyects
    resources :industrial_proyects
    resources :contacts
  end


  resources :contacts,  only: [:create]
  resources :hogar_proyects, only: [:index, :show]
  resources :hadjuntos, only: [:create, :destroy, :new]
  resources :industrial_proyects, only: [:index, :show]
  resources :iadjuntos, only: [:create, :destroy, :new]
  

  root 'home#index'

  get 'industria/index'

  get 'hogar/index'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/hogar_proyect.rb
class HogarProyect < ApplicationRecord
  has_many :hadjuntos
end

app/controllers/hogar_proyects_controller.rb
class HogarProyectsController < ApplicationController
  before_action :set_hogar_proyect, only: [:show, :edit, :update, :destroy]

  # GET /hogar_proyects
  # GET /hogar_proyects.json
  def index
    @hogar_proyects = HogarProyect.all
  end

  # GET /hogar_proyects/1
  # GET /hogar_proyects/1.json
  def show
    @hadjunto = Hadjunto.new
  end

  # GET /hogar_proyects/new
  def new
    @hogar_proyect = HogarProyect.new
  end

  # GET /hogar_proyects/1/edit
  def edit
  end

  # POST /hogar_proyects
  # POST /hogar_proyects.json
  def create
    @hogar_proyect = HogarProyect.new(hogar_proyect_params)

    respond_to do |format|
      if @hogar_proyect.save
        format.html { redirect_to @hogar_proyect, notice: 'Hogar proyect was successfully created.' }
        format.json { render :show, status: :created, location: @hogar_proyect }
      else
        format.html { render :new }
        format.json { render json: @hogar_proyect.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hogar_proyects/1
  # PATCH/PUT /hogar_proyects/1.json
  def update
    respond_to do |format|
      if @hogar_proyect.update(hogar_proyect_params)
        format.html { redirect_to @hogar_proyect, notice: 'Hogar proyect was successfully updated.' }
        format.json { render :show, status: :ok, location: @hogar_proyect }
      else
        format.html { render :edit }
        format.json { render json: @hogar_proyect.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hogar_proyects/1
  # DELETE /hogar_proyects/1.json
  def destroy
    @hogar_proyect.destroy
    respond_to do |format|
      format.html { redirect_to hogar_proyects_url, notice: 'Hogar proyect was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hogar_proyect
      @hogar_proyect = HogarProyect.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hogar_proyect_params
      params.require(:hogar_proyect).permit(:name, :description, :large_description)
    end
end

app/helpers/hogar_proyects_helper.rb
module HogarProyectsHelper
end

app/views/hogar_proyects/_form.html.erb
<%= form_for(hogar_proyect) do |f| %>
  <% if hogar_proyect.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(hogar_proyect.errors.count, "error") %> prohibited this hogar_proyect from being saved:</h2>

      <ul>
      <% hogar_proyect.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :large_description %>
    <%= f.text_area :large_description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/hogar_proyects/edit.html.erb
<h1>Editing Hogar Proyect</h1>

<%= render 'form', hogar_proyect: @hogar_proyect %>

<%= link_to 'Show', @hogar_proyect %> |
<%= link_to 'Back', hogar_proyects_path %>

app/views/hogar_proyects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Hogar Proyects</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Large description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @hogar_proyects.each do |hogar_proyect| %>
      <tr>
        <td><%= hogar_proyect.name %></td>
        <td><%= hogar_proyect.description %></td>
        <td><%= hogar_proyect.large_description %></td>
        <td><%= link_to 'Show', hogar_proyect %></td>
        <td><%= link_to 'Edit', edit_hogar_proyect_path(hogar_proyect) %></td>
        <td><%= link_to 'Destroy', hogar_proyect, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if admin_signed_in? %>
  <%= link_to 'New Hogar Proyect', new_hogar_proyect_path %>
<% end %>

app/views/hogar_proyects/new.html.erb
<h1>New Hogar Proyect</h1>

<%= render 'form', hogar_proyect: @hogar_proyect %>

<%= link_to 'Back', hogar_proyects_path %>

app/views/hogar_proyects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @hogar_proyect.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @hogar_proyect.description %>
</p>

<p>
  <strong>Large description:</strong>
  <%= @hogar_proyect.large_description %>
</p>

<% if admin_signed_in? %>
  <%= render 'hadjuntos/form', hogar_proyect_id: @hogar_proyect.id %>
<% end %>
<ul>
  <% @hogar_proyect.hadjuntos.each do |li| %>
    <li>
      <p>
        <%= image_tag (li.imagen.url) %>
          <span><%=  link_to "x", li, method: :delete %></span>
        </p>
    </li>
  <% end %>
</ul>

<%= link_to 'Edit', edit_hogar_proyect_path(@hogar_proyect) %> |
<%= link_to 'Back', hogar_proyects_path %>